name = input("Whats your name?")
print(f"Hello {name}")
print("I'm going to tell you a story but I need your help")
print("______________________________________________________________________")
number = input("Give me a number:")
date = input("Give me a date, for example december 5th 2025:")
animal = input("Give me an animal:")
name1 = input("Give me a random name:")
verb = input("Give me a verb ending in ing:")
emotion = input("Give me an emotion ending in ed:")
item = input("Give me a item:")
animal2 = input("Give me a new animal:")
emotion1 = input("Give me a different emotion:")
facial = input("give a me facial expression ending in ed, an example would be squinted or smiled:")
emotion2 = input("Now give me another emotion ending ly:")
print("Ok, great! Lets see your story!")
print("______________________________________________________________________")
print(f"{number} years ago, on {date} a young {animal} named {name1} was walking down the street")
print(f"Suddenly, out of nowhere, a figure came {verb} by, bumping into {name1}")
print(f"poor {name1} was so {emotion} they dropped the {item} they had been carrying")
print(f"Unfortunatly, the {animal2} who had bumped {name1} didn't care")
print(f"this made {name1} very {emotion1} so {name1} chased after the {animal2}")
print(f"Thankfully the {animal2} wasn't very fast so {name1} caught up quickly")
print(f"{name1} {facial} at the {animal2} who {emotion2} apologized")
print("The End!")
input("")